config/routes.rb
Rails.application.routes.draw do
  resources :items

  get 'example' => 'items#index'

end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
 has_many :titles, dependent: :destroy
 has_many :codes , dependent: :destroy
 accepts_nested_attributes_for :titles, :codes
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :item
end

app/models/title.rb
class Title < ActiveRecord::Base
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.titles.build
    @item.codes.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:price, :total_sold, titles_attributes: [:id, :name, :_destroy], codes_attributes: [:id, :code_numbere, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_code_fields.html.erb
<label>Code number </label>
<%= f.text_field :code_numbere %>
<br><br>
<%= link_to_remove_association "remove code", f %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new-titles">
    <%= f.fields_for :titles do |form| %>
      <%= render partial: "title_fields", locals: {f: form} %>
    <% end %>
  </div>
  <%= link_to_add_association 'Add Title', f, :titles, 'data-association-insertion-node' => ".new-titles", 'data-association-insertion-method' => "append", :wrap_object => @item.titles.build %>
  <br><br>
  <div class="new-codes">
    <%= f.fields_for :codes do |form| %>
      <%= render partial: "code_fields", locals: {f: form} %>
    <% end %>
  </div>
  <%= link_to_add_association 'Add Code', f, :codes, 'data-association-insertion-node' => ".new-codes", 'data-association-insertion-method' => "append", :wrap_object => @item.codes.build %>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :total_sold %><br>
    <%= f.number_field :total_sold %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_title_fields.html.erb
<label>Name </label>
<%= f.text_field :name %>
<br><br>
<%= link_to_remove_association "remove title", f %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Total sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.price %></td>
        <td><%= item.total_sold %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->

<%#= link_to 'New Item', new_item_path %>
<div ng-app='app.exampleApp' ng-controller='ExampleCtrl'>
  
  <p>Value from ExampleCtrl:</p>
  <p>{{ exampleValue }}</p>
  
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Total sold:</strong>
  <%= @item.total_sold %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Api</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>